### PR TITLE
do not optimize build deps

### PR DESCRIPTION
**Pull request by japaric**
this may make CI faster

### CODE REVIEW

**Comment by japaric** [comment]
CI times: this PR, build from scratch: https://travis-ci.org/github/rtfm-rs/cortex-m-rtfm/builds/691455729

CI times: this PR, incremental re-build (*): https://travis-ci.org/github/rtfm-rs/cortex-m-rtfm/builds/691464099

CI times last PR: https://travis-ci.org/github/rtfm-rs/cortex-m-rtfm/builds/678193581

(*) I only modified Cargo.toml so it may not be a fair comparison

**Comment by japaric** [comment]
CI times: this PR, incremental re-build after small codegen change: https://travis-ci.org/github/rtfm-rs/cortex-m-rtfm/builds/691468213

it seems this change cuts down the completion time of some build jobs by ~2 mins. It does break the MSRV build as it is but that can be addressed in ci/script.sh.

**Comment by korken89** [comment]
bors retry

**Comment by korken89** [comment]
Right, MSRV failing. Maybe keep this until 0.6 unless someone has time to exclude it from MSRV.

**Comment by korken89** [comment]
bors retry

**Comment by korken89** [comment]
bors retry

**Pull request merged**
